import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import dynamic from "next/dynamic";
const TryApi = dynamic(() => import("../components/TryApi"));
const NavHome = dynamic(() => import("../components/NavHome"));
const NavShade = dynamic(() => import("../components/NavShade"));
const NavJavascript = dynamic(() => import("../components/NavJavascript"));
const NavTypescript = dynamic(() => import("../components/NavTypescript"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Xhadr Ui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavHome />
        <hr
          style={{
            backgroundColor: "#1F1F1F",
            height: 8,
            borderColor: "#3DD4AE",
          }}
        />
        <section className="backdrop-blur-3xl bg-gradient-to-tr from-stone-800 via-cyan-900 to-stone-900 text-cyan-100 ">
          <div className="container mx-auto flex flex-col items-center px-4 py-6 text-center lg:px-32 ">
            <h1 className="text-4xl font-bold leading-none sm:text-5xl font-serif">
              <div className="btn btn-circle animate-ping"></div> Rapidly build
              modern projects with <br></br>
              <span className="text-cyan-400">Xhadr-Api</span>{" "}
              <div className="btn btn-square animate-ping"></div>
            </h1>

            <p className="px-8 mt-8 mb-12 text-lg font-mono font-semibold">
              A
              <span className="text-cyan-400 hover:text-opacity-75">
                <Link href="https://nextjs.org/"> Next-Js </Link>
              </span>
              based
              <span className="text-cyan-400 hover:text-opacity-75">
                <Link href="https://restfulapi.net/"> REST-api </Link>
              </span>
              <br></br>
              <i className="text-xs">(representational state transfer)</i>
            </p>
            <div className="form-control w-full max-w-xs">
              <TryApi />
            </div>
          </div>
          <hr
            style={{
              backgroundColor: "#1F1F1F",
              height: 8,
              borderColor: "#3DD4AE",
            }}
          />
        </section>
        <section className="bg-stone-50">
          <div className="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
            <div className="max-w-xl mb-10 md:mx-auto sm:text-center lg:max-w-2xl md:mb-12">
              <h2 className="max-w-lg mb-6 font-semibold text-3xl font-serif leading-none tracking-tight text-cyan-700 sm:text-4xl md:mx-auto">
                Quick & Easy Implementaion
              </h2>
              <p className=" text-cyan-700 md:text-lg font-mono text-xs">
                A REST API is an application programming interface (API or web
                API) that conforms to the constraints of REST architectural
                style and allows for interaction with RESTful web services.
              </p>
            </div>
            <div className="grid max-w-screen-lg gap-8 lg:grid-cols-2 sm:mx-auto">
              <div className="grid grid-cols-2 gap-5">
                <Image
                  className="object-cover w-full h-56 col-span-2 rounded-lg shadow-lg shadow-yellow-800 hover:scale-105 transition-all duration-250"
                  src="/nsfw.png"
                  alt=""
                  width={720}
                  height={500}
                />
                <Image
                  className="object-cover w-full h-48 rounded-lg shadow-lg shadow-neutral-800 hover:scale-105 transition-all duration-250"
                  src="/hentai.png"
                  alt=""
                  width={500}
                  height={720}
                />
                <Image
                  className="object-cover w-full h-48 rounded-lg shadow-lg shadow-green-800 hover:scale-105 transition-all duration-250"
                  src="/animation.png"
                  alt=""
                  width={500}
                  height={720}
                />
              </div>
              <div className="flex flex-col justify-center">
                <div className="pb-4 mb-4 border-b">
                  <h6 className="mb-2 leading-5 text-2xl font-serif font-bold text-cyan-700 text-justify">
                    What does Xhadr-api Offer?
                  </h6>
                  <p className="text-1xl text-cyan-900 font-sans hover:text-cyan-600 hover:font-semibold text-justify">
                    <span className="text-cyan-700 italic font-bold">
                      With{" "}
                    </span>
                    xhadr-api you can fetch different types of informations
                    without needing to install any dependencies or worrying
                    about servers or configurations.<br></br>
                    <span className="text-cyan-700 italic font-bold">
                      Just{" "}
                    </span>
                    use any method to fetch the api endpoints and you will be
                    delighted with a perfect constructed object as a response
                    from that endpoint of choice.<br></br>
                    <span className="text-cyan-700 italic font-bold">
                      Xhadr-Api{" "}
                    </span>
                    has many endpoints like animation, anime, hentai, youtube
                    music, youtube video, youtube search, nsfw and many more
                    upcoming.
                  </p>
                </div>
              </div>
            </div>
          </div>{" "}
          <hr
            style={{
              backgroundColor: "#3DD4AE",
              height: 8,
            }}
          />
        </section>

        <hr
          style={{
            backgroundColor: "#1F1F1F",
            height: 8,
          }}
        />
        <footer className="footer footer-center  w-full p-4 bg-gradient-to-tr bg-stone-900 text-yellow-100">
          <div className="text-center">
            {" "}
            <Link href="/">
              <button className="inline-block px-20 py-3 mt-8 text-sm font-medium text-stone-200 border border-stone-600 rounded-lg bg-stone-900 hover:bg-stone-600 hover:text-white focus:outline-none focus:ring active:bg-stone-500">
                To Home
              </button>
            </Link>
            <br></br> <br></br>
            <p>
              Copyright © 2022 -
              <a className="font-semibold" href="mailto:m.sohanemon@gmail.com">
                Xhadr
              </a>
            </p>{" "}
          </div>
        </footer>
      </main>
    </>
  );
}
