import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
export default function typescript() {
  return (
    <>
      <Head>
        <title>Xhadr Ui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="bg-gradient-to-tr from-gray-900 via-blue-800 to-gray-900 text-blue-100">
          <div className="container mx-auto flex flex-col items-center px-4 py-16 text-center md:py-32 md:px-10 lg:px-32 xl:max-w-3xl">
            <h1 className="text-4xl font-bold leading-none sm:text-5xl font-serif">
              Rapidly build modern projects with<br></br>
              <span className="text-blue-400">Xhadr-Api</span>
            </h1>
            <p className="px-8 mt-8 mb-12 text-lg font-mono">
              A <span className="text-blue-400"> Next-js </span> based
              <span className="text-blue-400"> RESTFul Api </span>
              <i className="text-xs">(representational state transfer)</i>
            </p>
            <div className="sm:mb-8 sm:flex sm:justify-center">
              <div className="animate-pulse relative overflow-hidden rounded-lg-b-lg py-1.5 px-4 text-sm leading-6 ring-1 ring-blue-600 hover:ring-blue-500">
                <span className="text-blue-600 font-bold">
                  Designed & Developed by Xhadr
                </span>
              </div>
            </div>
          </div>
          <hr
            style={{
              backgroundColor: "#18337C",
              height: 8,
              borderColor: "#91A2B4",
            }}
          />
        </section>
        <section className="bg-[url(https://i.postimg.cc/cL8NgHxR/hentai.jpg)] bg-cover bg-center bg-no-repeat">
          <div className="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
            <div className="max-w-xl mb-10 md:mx-auto sm:text-center lg:max-w-2xl md:mb-12">
              <h2 className="max-w-lg mb-6 font-serif text-4xl font-bold leading-none tracking-tight text-blue-300 sm:text-5xl md:mx-auto">
                Available api endpoints
              </h2>
              <p className="text-base text-blue-400 md:text-lg font-mono">
                <i>use these below endpoints to get response from the api</i>
              </p>
            </div>
            <div className="max-w-lg space-y-3 sm:mx-auto lg:max-w-xl">
              <div className="hover:animate-pulse flex items-center p-2 transition-colors duration-500 border rounded-lg shadow-blue-200 shadow-sm group bg-stone-900 hover:bg-blue-400 hover:border-blue-400">
                <div className="mr-2">
                  <svg
                    className="w-6 h-6 transition-colors duration-500 text-blue-400 group-hover:text-white group-hover:bg-neutral-900 rounded-full sm:w-8 sm:h-8"
                    stroke="currentColor"
                    viewBox="0 0 52 52"
                  >
                    <polygon
                      strokeWidth="3"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      fill="none"
                      points="29 13 14 29 25 29 23 39 38 23 27 23"
                    ></polygon>
                  </svg>
                </div>
                <span className="text-white transition-colors duration-500 group-hover:text-white">
                  api/animation?q=
                </span>
              </div>
              <div className="hover:animate-pulse flex items-center p-2 transition-colors duration-500 border rounded-lg shadow-blue-200 shadow-sm group bg-stone-900 hover:bg-blue-400 hover:border-blue-400">
                <div className="mr-2">
                  <svg
                    className="w-6 h-6 transition-colors duration-500 text-blue-400 group-hover:text-white group-hover:bg-neutral-900 rounded-full sm:w-8 sm:h-8"
                    stroke="currentColor"
                    viewBox="0 0 52 52"
                  >
                    <polygon
                      strokeWidth="3"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      fill="none"
                      points="29 13 14 29 25 29 23 39 38 23 27 23"
                    ></polygon>
                  </svg>
                </div>
                <span className="text-white transition-colors duration-500 group-hover:text-white">
                  api/youtube?q=
                </span>
              </div>
              <div className="hover:animate-pulse flex items-center p-2 transition-colors duration-500 border rounded-lg shadow-blue-200 shadow-sm group bg-stone-900 hover:bg-blue-400 hover:border-blue-400">
                <div className="mr-2">
                  <svg
                    className="w-6 h-6 transition-colors duration-500 text-blue-400 group-hover:text-white group-hover:bg-neutral-900 rounded-full sm:w-8 sm:h-8"
                    stroke="currentColor"
                    viewBox="0 0 52 52"
                  >
                    <polygon
                      strokeWidth="3"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      fill="none"
                      points="29 13 14 29 25 29 23 39 38 23 27 23"
                    ></polygon>
                  </svg>
                </div>
                <span className="text-white transition-colors duration-500 group-hover:text-white">
                  api/hentai?q=
                </span>
              </div>
              <div className="hover:animate-pulse flex items-center p-2 transition-colors duration-500 border rounded-lg shadow-blue-200 shadow-sm group bg-stone-900 hover:bg-blue-400 hover:border-blue-400">
                <div className="mr-2">
                  <svg
                    className="w-6 h-6 transition-colors duration-500 text-blue-400 group-hover:text-white group-hover:bg-neutral-900 rounded-full sm:w-8 sm:h-8"
                    stroke="currentColor"
                    viewBox="0 0 52 52"
                  >
                    <polygon
                      strokeWidth="3"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      fill="none"
                      points="29 13 14 29 25 29 23 39 38 23 27 23"
                    ></polygon>
                  </svg>
                </div>
                <span className="text-white transition-colors duration-500 group-hover:text-white">
                  api/anime?q=
                </span>
              </div>
              <div className="hover:animate-pulse flex items-center p-2 transition-colors duration-500 border rounded-lg shadow-blue-200 shadow-sm group bg-stone-900 hover:bg-blue-400 hover:border-blue-400">
                <div className="mr-2">
                  <svg
                    className="w-6 h-6 transition-colors duration-500 text-blue-400 group-hover:text-white group-hover:bg-neutral-900 rounded-full sm:w-8 sm:h-8"
                    stroke="currentColor"
                    viewBox="0 0 52 52"
                  >
                    <polygon
                      strokeWidth="3"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      fill="none"
                      points="29 13 14 29 25 29 23 39 38 23 27 23"
                    ></polygon>
                  </svg>
                </div>
                <span className="text-white transition-colors duration-500 group-hover:text-white">
                  api/nsfw?q=
                </span>
              </div>
            </div>
          </div>
          <hr
            style={{
              backgroundColor: "#18337C",
              height: 8,
              borderColor: "#91A2B4",
            }}
          />
        </section>
        <section className="text-gray-400 bg-gradient-to-tr from-gray-900 via-stone-800 to-gray-900 body-font">
          <div className="container px-5 py-24 mx-auto flex flex-wrap">
            <div className="flex flex-col text-center w-full mb-20">
              <h2 className="text-xs text-blue-400 tracking-widest font-medium title-font mb-1">
                ROOF PARTY POLAROID
              </h2>
              <h1 className="sm:text-3xl text-2xl font-medium title-font text-white">
                Master Cleanse Reliac Heirloom
              </h1>
            </div>
            <div className="flex flex-wrap -m-4">
              <div className="p-4 md:w-1/3">
                <div className="hover:animate-pulse hover:bg-gray-800 flex rounded-lg h-full bg-gray-700 bg-opacity-60 p-8 flex-col">
                  <div className="flex items-center mb-3">
                    <div className="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-blue-500 text-white flex-shrink-0">
                      <svg
                        fill="none"
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        className="w-5 h-5"
                        viewBox="0 0 24 24"
                      >
                        <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                      </svg>
                    </div>
                    <h2 className="text-white text-lg title-font font-medium">
                      Method 1 Using Axios: <br></br>
                      <span className="italic text-sm text-blue-200">{`import axios from "axios";`}</span>
                    </h2>
                  </div>
                  <div className="flex-grow">
                    <p className="leading-relaxed text-base">
                      In this example we will be using{" "}
                      <span className="font-semibold text-blue-400">
                        {" "}
                        api/animation{" "}
                      </span>
                      endpoint.<br></br>
                      <span className="font-semibold text-blue-400">
                        {" "}
                        ?q={" "}
                      </span>{" "}
                      is the querry that api/animation takes.
                    </p>
                    <a className="mt-3 text-blue-400 inline-flex items-center">
                      Continue
                      <svg
                        fill="none"
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        className="w-4 h-4 ml-2"
                        viewBox="0 0 24 24"
                      >
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className="p-4 md:w-1/3">
                <div className="hover:animate-pulse hover:bg-gray-800 flex rounded-lg h-full bg-gray-700 bg-opacity-60 p-8 flex-col">
                  <div className="flex items-center mb-3">
                    <div className="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-blue-500 text-white flex-shrink-0">
                      <svg
                        fill="none"
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        className="w-5 h-5"
                        viewBox="0 0 24 24"
                      >
                        <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                        <circle cx="12" cy="7" r="4"></circle>
                      </svg>
                    </div>
                    <h2 className="text-white text-lg title-font font-medium">
                      Method 2 Using Request: <br></br>
                      <span className="italic text-sm text-blue-200">{`const request = require("request");`}</span>
                    </h2>
                  </div>
                  <div className="flex-grow">
                    <p className="leading-relaxed text-base">
                      In this example we will be using{" "}
                      <span className="font-semibold text-blue-400">
                        {" "}
                        api/nsfw{" "}
                      </span>
                      endpoint.<br></br>
                      <span className="font-semibold text-blue-400">
                        {" "}
                        ?q={" "}
                      </span>{" "}
                      is the querry that api/nsfw takes.
                    </p>
                    <a className="mt-3 text-blue-400 inline-flex items-center">
                      Continue
                      <svg
                        fill="none"
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        className="w-4 h-4 ml-2"
                        viewBox="0 0 24 24"
                      >
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div className="p-4 md:w-1/3">
                <div className="hover:animate-pulse hover:bg-gray-800 flex rounded-lg h-full bg-gray-700 bg-opacity-60 p-8 flex-col">
                  <div className="flex items-center mb-3">
                    <div className="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-blue-500 text-white flex-shrink-0">
                      <svg
                        fill="none"
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        className="w-5 h-5"
                        viewBox="0 0 24 24"
                      >
                        <circle cx="6" cy="6" r="3"></circle>
                        <circle cx="6" cy="18" r="3"></circle>
                        <path d="M20 4L8.12 15.88M14.47 14.48L20 20M8.12 8.12L12 12"></path>
                      </svg>
                    </div>
                    <h2 className="text-white text-lg title-font font-medium">
                      Method 3 Using Unirest: <br></br>
                      <span className="italic text-sm text-blue-200">{`const unirest = require("unirest");`}</span>
                    </h2>
                  </div>
                  <div className="flex-grow">
                    <p className="leading-relaxed text-base">
                      In this example we will be using{" "}
                      <span className="font-semibold text-blue-400">
                        {" "}
                        api/hentai{" "}
                      </span>
                      endpoint.<br></br>
                      <span className="font-semibold text-blue-400">
                        {" "}
                        ?q={" "}
                      </span>{" "}
                      is the querry that api/hentai takes.
                    </p>
                    <a className="mt-3 text-blue-400 inline-flex items-center">
                      Continue
                      <svg
                        fill="none"
                        stroke="currentColor"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        className="w-4 h-4 ml-2"
                        viewBox="0 0 24 24"
                      >
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>{" "}
        <hr
          style={{
            backgroundColor: "#1F1F1F",
            height: 8,
          }}
        />
        <footer
          aria-label="Site Footer"
          className="bg-gradient-to-tr from-gray-900 via-blue-800 to-gray-900 text-blue-100"
        >
          <div className="max-w-screen-xl px-4 pt-16 pb-8 mx-auto sm:px-6 lg:px-8 lg:pt-24">
            <div className="text-center">
              <h2 className="text-5xl font-serif font-bold text-blue-400 sm:text-7xl">
                Xhadr-Api
              </h2>
              <div>
                <Link href="/">
                  <button className="animate-bounce inline-block px-20 py-3 mt-8 text-sm font-medium text-blue-600 border border-blue-600 rounded-lg bg-stone-900 hover:bg-blue-600 hover:text-white focus:outline-none focus:ring active:bg-blue-500">
                    Go Home
                  </button>
                </Link>
              </div>
            </div>

            <div className="pt-8 mt-16 border-t border-blue-100 sm:flex sm:items-center sm:justify-between lg:mt-24">
              <nav aria-label="Footer Navigation - Support">
                <ul className="flex flex-wrap justify-center gap-4 text-xs lg:justify-end">
                  <li>
                    <Link
                      href="#"
                      className="text-blue-500 transition hover:opacity-75"
                    >
                      Terms & Conditions
                    </Link>
                  </li>

                  <li>
                    <Link
                      href="#"
                      className="text-blue-500 transition hover:opacity-75"
                    >
                      Privacy Policy
                    </Link>
                  </li>

                  <li>
                    <Link
                      href="#"
                      className="text-blue-500 transition hover:opacity-75"
                    >
                      Cookies
                    </Link>
                  </li>
                </ul>
              </nav>

              <ul className="flex justify-center gap-6 mt-8 sm:mt-0 lg:justify-end">
                <li>
                  <Link
                    href="/"
                    rel="noreferrer"
                    target="_blank"
                    className="text-blue-700 transition hover:opacity-75"
                  >
                    <span className="sr-only">Facebook</span>

                    <svg
                      className="w-6 h-6"
                      fill="currentColor"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                        clipRule="evenodd"
                      />
                    </svg>
                  </Link>
                </li>

                <li>
                  <Link
                    href="/"
                    rel="noreferrer"
                    target="_blank"
                    className="text-blue-700 transition hover:opacity-75"
                  >
                    <span className="sr-only">Instagram</span>

                    <svg
                      className="w-6 h-6"
                      fill="currentColor"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z"
                        clipRule="evenodd"
                      />
                    </svg>
                  </Link>
                </li>

                <li>
                  <Link
                    href="/"
                    rel="noreferrer"
                    target="_blank"
                    className="text-blue-700 transition hover:opacity-75"
                  >
                    <span className="sr-only">Twitter</span>

                    <svg
                      className="w-6 h-6"
                      fill="currentColor"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                    >
                      <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
                    </svg>
                  </Link>
                </li>

                <li>
                  <Link
                    href="/"
                    rel="noreferrer"
                    target="_blank"
                    className="text-blue-700 transition hover:opacity-75"
                  >
                    <span className="sr-only">GitHub</span>

                    <svg
                      className="w-6 h-6"
                      fill="currentColor"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                        clipRule="evenodd"
                      />
                    </svg>
                  </Link>
                </li>

                <li>
                  <Link
                    href="/"
                    rel="noreferrer"
                    target="_blank"
                    className="text-blue-700 transition hover:opacity-75"
                  >
                    <span className="sr-only">Dribbble</span>

                    <svg
                      className="w-6 h-6"
                      fill="currentColor"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z"
                        clipRule="evenodd"
                      />
                    </svg>
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
