import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import dynamic from "next/dynamic";

const Animation = dynamic(() => import("../components/examples/Animation"));
const Youtube = dynamic(() => import("../components/examples/Youtube"));
const Shorten = dynamic(() => import("../components/examples/Shorten"));
const Hentai = dynamic(() => import("../components/examples/Hentai"));
const Anime = dynamic(() => import("../components/examples/Anime"));
const Nsfw = dynamic(() => import("../components/examples/Nsfw"));

export default function magneum() {
  return (
    <>
      <Head>
        <title>Magneum Ui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b from-zinc-900 to-slate-900 font-serif">
        <section>
          <div className="relative block w-full mx-auto md:mt-0">
            <Image
              alt="blob"
              width={700}
              height={700}
              src="/Next_By_Vercel_White.png"
              className="max-w-xs m-auto md:max-w-2xl animate-pulse"
            ></Image>
            <div className="relative flex items-center backdrop-blur-3xl ">
              <div className="container relative flex flex-col items-center justify-between px-6 py-8 mx-auto">
                <div className="flex flex-col">
                  <h1 className="w-full text-4xl font-light text-center text-blue-400 uppercase sm:text-5xl hover:text-blue-50">
                    Get Started With Magneum Api
                  </h1>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* ============================================================================================================== */}
        <section>
          <div className="container px-6 mx-auto">
            <h1 className="text-2xl text-gray-400 capitalize lg:text-3xl text-center">
              explore all <br></br> awesome{" "}
              <span className="underline decoration-blue-500 text-blue-400">
                magneum Endpoints
              </span>
            </h1>
            <h1 className="italic text-md font-light text-gray-400 capitalize lg:text-lg text-center">
              Api Endpoint{" "}
              <span className="text-blue-400 lowercase">
                https://magneum.vercel.app/api/
              </span>
            </h1>
            {/* ============================================================================================================== */}
            <div className="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 md:grid-cols-2 xl:grid-cols-3">
              <div className="p-8 space-y-3 border-2 border-blue-400  rounded-xl hover:scale-105 duration-500 hover:contrast-125 bg-slate-900">
                <span className="inline-block text-blue-500 ">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-8 h-8"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
                    />
                  </svg>
                </span>
                <h1 className="text-lg text-blue-200 uppercase">Api/Shorten</h1>
                <p className="text-gray-500 ">
                  <Shorten />
                </p>
              </div>
              {/* ============================================================================================================== */}
              <div className="p-8 space-y-3 border-2 border-blue-400  rounded-xl hover:scale-105 duration-500 hover:contrast-125 bg-slate-900">
                <span className="inline-block text-blue-500 ">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-8 h-8"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
                    />
                  </svg>
                </span>
                <h1 className="text-lg text-blue-200 uppercase">Api/Anime</h1>
                <p className="text-gray-500 ">
                  <Anime />
                </p>
              </div>
              {/* ============================================================================================================== */}
              <div className="p-8 space-y-3 border-2 border-blue-400  rounded-xl hover:scale-105 duration-500 hover:contrast-125 bg-slate-900">
                <span className="inline-block text-blue-500 ">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-8 h-8"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
                    />
                  </svg>
                </span>
                <h1 className="text-lg text-blue-200 uppercase">Api/Youtube</h1>
                <p className="text-gray-500 ">
                  <Youtube />
                </p>
              </div>
            </div>
            {/* ============================================================================================================== */}
            <div className="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 md:grid-cols-2 xl:grid-cols-3">
              <div className="p-8 space-y-3 border-2 border-blue-400  rounded-xl hover:scale-105 duration-500 hover:contrast-125 bg-slate-900">
                <span className="inline-block text-blue-500 ">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-8 h-8"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
                    />
                  </svg>
                </span>
                <h1 className="text-lg text-blue-200 uppercase">
                  Api/Animation
                </h1>
                <p className="text-gray-500 ">
                  <Animation />
                </p>
              </div>
              {/* ============================================================================================================== */}
              <div className="p-8 space-y-3 border-2 border-blue-400  rounded-xl hover:scale-105 duration-500 hover:contrast-125 bg-slate-900">
                <span className="inline-block text-blue-500 ">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-8 h-8"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
                    />
                  </svg>
                </span>
                <h1 className="text-lg text-blue-200 uppercase">Api/Hentai</h1>
                <p className="text-gray-500 ">
                  <Hentai />
                </p>
              </div>
              {/* ============================================================================================================== */}
              <div className="p-8 space-y-3 border-2 border-blue-400  rounded-xl hover:scale-105 duration-500 hover:contrast-125 bg-slate-900">
                <span className="inline-block text-blue-500 ">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-8 h-8"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
                    />
                  </svg>
                </span>
                <h1 className="text-lg text-blue-200 uppercase">Api/Nsfw</h1>
                <p className="text-gray-500 ">
                  <Nsfw />
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="footer footer-center p-10 bg-slate-900 text-base-content rounded">
        <div>
          <p className="font-bold italic text-slate-400">
            Copyright © 2023 - All right reserved by Magneum Industries Ltd
          </p>
        </div>
      </footer>
    </>
  );
}
